# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d07242e60d151198c242bcc8805de155ff540456a6252675f454bdd1d97f69fa5b11abd0e4be6610523b20ba6fa118bb6727822dd3db0afb52ac25864880a091

test:
  secret_key_base: b6579b5c4a9392e9caa62a8abb02566845dd7d52268880415fba51b7b4eafc57fb91981614001ba9bf4f6066176eea74ec07de6cb73816df58ea5ebeb7012523

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
